

static const char server_sertificate[] =
"-----BEGIN CERTIFICATE-----\n"
"MIID/zCCAuegAwIBAgIJAP1U0TmwVMOHMA0GCSqGSIb3DQEBCwUAMIGVMQswCQYD\n"
"VQQGEwJmaTEQMA4GA1UECAwHdXVzaW1hYTERMA8GA1UEBwwISGVsc2lua2kxGDAW\n"
"BgNVBAoMD0NocmlzdGVyIEVraG9sbTEPMA0GA1UECwwGSGFja2VyMQ8wDQYDVQQD\n"
"DAZDaHJpc3UxJTAjBgkqhkiG9w0BCQEWFmNocmlzdGVyLmVraG9sbUBpa2kuZmkw\n"
"HhcNMTYxMTE1MDUxMDU0WhcNMTcxMTE1MDUxMDU0WjCBlTELMAkGA1UEBhMCZmkx\n"
"EDAOBgNVBAgMB3V1c2ltYWExETAPBgNVBAcMCEhlbHNpbmtpMRgwFgYDVQQKDA9D\n"
"aHJpc3RlciBFa2hvbG0xDzANBgNVBAsMBkhhY2tlcjEPMA0GA1UEAwwGQ2hyaXN1\n"
"MSUwIwYJKoZIhvcNAQkBFhZjaHJpc3Rlci5la2hvbG1AaWtpLmZpMIIBIjANBgkq\n"
"hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA03/69myscadIqv/2Wi16LQALigeHkLpX\n"
"tiUAHej81gfqqpAXK1Vt0/9du1rE/CD4bYMGwDYdKSkrtvldVgswkB+ktQEY+sSH\n"
"5RHcQYuZgRzM7uUmlzdkWXxhES/SFXv2afgJuP8V2cIf3FBBtoO8bRv58z6Jd1U/\n"
"PA8nT+MbtzzSVC+qrIzhEcpaUalUalAb8HXvWogvRiotLZ9FQEx3gg21eZ37tTss\n"
"dVGRDMNE4/ZMlSNVOub4BblceCSnIK7px2154mgGqVZbPQ9BzRvJF8jXNICGzXfr\n"
"IQTJwB6o2aJ6HTQtra9okPbodaz8FGK8Gfxg3t+tnJN2QiHncgpbGwIDAQABo1Aw\n"
"TjAdBgNVHQ4EFgQUxYMDviih5W7k5FiqdpZTJZoeaqowHwYDVR0jBBgwFoAUxYMD\n"
"viih5W7k5FiqdpZTJZoeaqowDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC\n"
"AQEAJtLur/y5/Spv+ayZot182s2nI/h2g2d04PjhpgPuQCrFQUGNQ4GrcOoO9OmL\n"
"yTCAEbkfigUM6+8MmTX7oka5cCPAQkt5mom+DSx6oH94K5dh7L+aIUo5sz4K9W/1\n"
"uqBbzWSnPYzkNgslPjFLcUKbPIXmE4/riZZE4uvp8IvwBB5+ZMLLN3ghyqClqlha\n"
"bomMRWv5uYbFbJKMAoatJhpjDByNsHjfaBlCNiOvGhmLr7J2ZCugVddWswBjw1SW\n"
"r4HV7yfqujtH2fB44uNNO7Zsrrv58IOmA93IGy72AesznqPz5rdmD9ZhuHFFbYKI\n"
"sryepWot+ccZ5EkyLIjDsJ8X2Q==\n"
"-----END CERTIFICATE-----\n";


