/*
 * WS_Error.h
 *
 *  Created on: Sep 25, 2014
 *      Author: Tuan Vu
 */

#ifndef WS_ERROR_H_
#define WS_ERROR_H_

typedef enum t_ErrorCode
{
	G_OK,
	G_ERROR_UNKOWN,
	G_ERROR_NOT_ENOUGH_MEMORY,
	G_ERROR_UNINITIALIZED,
	G_ERROR_UNABLE_OPEN_SOCKET,
	G_ERROR_UNABLE_CONNECT,
	G_ERROR_CONNECTION_REFUSED,
	G_ERROR_TIME_OUT,
	G_ERROR_UNABLE_SEND,
	G_ERROR_BUFFER_FULL,
	G_ERROR_UNABLE_RECEIVE,
	G_ERROR_INVALID_HTTP_RESPONSE,
	G_ERROR_LIST_EMPTY,
	G_ERROR_MESSAGE_WAS_NOT_SENT,
	G_ERROR_SSL_UNABLE_LOAD_CERTIFICATE,
	G_ERROR_SSL_UNABLE_CONNECT_SOCKET,
	G_ERROR_UNAUTHORIZED,
	G_ERROR_INVALID_CONNECTION_STRING,
	G_ERROR_SERVER_ERROR,
	G_ERROR_INVALID_VARIANT_TYPE,
	G_ERROR_INVALID_JSON_FORMAT

} t_ErrorCode;

void G_SetLastError(t_ErrorCode code);

void G_SetLastErrorExact(t_ErrorCode code, int exactCode);

t_ErrorCode G_GetLastError(void);

int G_GetExactCode(void);

#endif /* WS_ERROR_H_ */
